#!/usr/bin/env bash
# install packages I use
sudo pacman -S --needed base-devel whois dnsutils gvim zsh strace awesome alsa-utils chromium clang keychain tcpdump kexec-tools ghc openbsd-netcat xorg-server awesome clojure wpa_actiond mosh nmap ctags wget

# install yaourt with its dependencies, if not already installed
pacman -Q | grep -q package-query
if [ $? -ne 0 ]; then
  curl https://aur.archlinux.org/packages/pa/package-query/package-query.tar.gz | tar -zxf-
  cd package-query
  makepkg -s
  sudo pacman -U package-query-*.xz
  cd ..
fi

pacman -Q | grep -q yaourt
if [ $? -ne 0 ]; then
  curl https://aur.archlinux.org/packages/ya/yaourt/yaourt.tar.gz | tar -zxf-
  cd yaourt
  makepkg -s
  sudo pacman -U yaourt-*.xz
  cd ..
fi

yaourt -S physlock ttf-inconsolata-tz
