#!/usr/bin/env bash
# install packages I use
sudo pacman -S --needed base-devel whois dnsutils gvim zsh strace awesome alsa-utils chromium clang keychain tcpdump kexec-tools ghc openbsd-netcat xorg-server awesome clojure wpa_actiond mosh nmap ctags wget pass acpi acpid tor scrot transmission-cli hdparm pcsclite ccid iperf ifplugd lsof cpio parted fuse rsync cmake pulseaudio cronie perf firefox mongodb

# install yaourt with its dependencies, if not already installed
pacman -Q | grep -q package-query
if [ $? -ne 0 ]; then
  curl https://aur.archlinux.org/packages/pa/package-query/package-query.tar.gz | tar -zxf-
  cd package-query
  makepkg -s
  sudo pacman -U package-query-*.xz
  cd ..
  rm -rf package-query
fi

pacman -Q | grep -q yaourt
if [ $? -ne 0 ]; then
  curl https://aur.archlinux.org/packages/ya/yaourt/yaourt.tar.gz | tar -zxf-
  cd yaourt
  makepkg -s
  sudo pacman -U yaourt-*.xz
  cd ..
  rm -rf yaourt
fi

yaourt -S physlock ttf-inconsolata-dz scrub uuid google-talkplugin

mkdir -p "$HOME/.local/share/applications"
xdg-mime default /usr/share/applications/firefox.desktop x-scheme-handler/http
xdg-mime default /usr/share/applications/firefox.desktop x-scheme-handler/https
xdg-mime default /usr/share/applications/firefox.desktop text/html
